### ISSUE TITLE
Can I use part of nuscenes to train?

### ISSUE THREAD

**Issue by Michael-Yi-Rong** [cure-lab/MagicDrive#110]
The full dataset needs too much time. If so, how to sample? Thanks!

**Comment by CSUXA** [comment]
I'm sorry to bother you,but i was wondering if you could spare some time to answer my question.Because  i noticed that you have also been looking this project recently.
this is my question:When I run the demo/run.py,i got an error.
encoded_inputs["attention_mask"] = encoded_inputs["attention_mask"] + [0] * difference
OverflowError: cannot fit 'int' into an index-sized integer
if you are willing to help me,i would truly appreciate it.

**Comment by flymin** [comment]
Duplicated.
Please check #9.
