### ISSUE TITLE
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like ../MagicDrive-pretrained/SDv1.5mv-rawbox_2023-09-07_18-39_224x400/controlnet is not the path to a directory containing a config.json file.

### ISSUE THREAD

**Issue by CSUXA** [cure-lab/MagicDrive#119]
![屏幕截图 2024-11-26 092904](https://github.com/user-attachments/assets/4d6b1a1d-b383-43f1-bdcc-4568055d959f)
![屏幕截图 2024-11-26 093038](https://github.com/user-attachments/assets/e127dddc-1bbd-4e5e-b637-bf171acd9303)
I would like to test generating videos using your pre-trained model.However,when I run the code:python ./tools/test.py resume_from_checkpoint=/root/autodl-tmp/MagicDrive-video/pretrained/SDv1.5mv-rawbox-t_2023-12-04_17-51_2.0t_0.4.3E4-S77040 runner.validation_times=4 runner.pipeline_param.init_noise=rand_all ++dataset.data.val.ann_file=/root/autodl-tmp/MagicDrive-video/data/nuscenes_mmdet3d-12Hz/nuscenes_interp_12Hz_infos_val.pkl,an error occurs as shown in the figure.I have set up the directory as  you provided in the file.What I confuses me is that I should use the model in /root/autodl-tmp/MagicDrive-video/pretrained/SDv1.5mv-rawbox-t_2023-12-04_17-51_2.0t_0.4.3E4-S77040/weight-E4-S77040/unet/diffusion_pytorch_model.bin,but it actually load the model in /root/autodl-tmp/MagicDrive-video/MagicDrive-pretrained/SDv1.5mv-rawbox_2023-09-07_18-39_224x400/controlnet/diffusion_pytorch_model.bin,and the error occurs which is OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like ../MagicDrive-pretrained/SDv1.5mv-rawbox_2023-09-07_18-39_224x400/controlnet is not the path to a directory containing a config.json file.

**Comment by Miayui** [comment]
Maybe you can change the config "configs/model/SDv1.5mv-rawbox_t.yaml" line 12 "pretrained_magicdrive: **..**/MagicDrive-pretrained/SDv1.5mv-rawbox_2023-09-07_18-39_224x400" to "pretrained_magicdrive: **.**/MagicDrive-pretrained/SDv1.5mv-rawbox_2023-09-07_18-39_224x400" (select the first point in the path)

**Comment by flymin** [comment]
Yes, the default config will try to find models located here (as in the readme):
```
{ROOT}/../MagicDrive-pretrained/
└── SDv1.5mv-rawbox_2023-09-07_18-39_224x400
```
rather than `{ROOT}/MagicDrive-pretrained/`

**Comment by CSUXA** [comment]
> Maybe you can change the config "configs/model/SDv1.5mv-rawbox_t.yaml" line 12 "pretrained_magicdrive: **../**MagicDrive-pretrained/SDv1.5mv-rawbox_2023-09-07_18-39_224x400" to "pretrained_magicdrive: **./**MagicDrive-pretrained/SDv1.5mv-rawbox_2023-09-07_18-39_224x400" (**delete the first point in the path**)

I made the modifications according to your suggestion,but there is another mistake.Since I have  prepared the file as shown in the picture,I'm confused why the jpg file cannot be found. 
![屏幕截图 2024-11-26 201845](https://github.com/user-attachments/assets/bb83d27b-a63e-457e-adc4-d593b6776a5c)
![屏幕截图 2024-11-26 202014](https://github.com/user-attachments/assets/329eb7c8-8ffd-4aed-abfd-946bd6d2a7ec)

**Comment by Miayui** [comment]
Maybe the pkl file "nuscenes_interp_12Hz_infos_val.pkl" you used is&nbsp;provided by the author which contains full nuscenes, but you don't download full nuscenes?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cure-lab/MagicDrive"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月26日(星期二) 晚上8:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cure-lab/MagicDrive] OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like ../MagicDrive-pretrained/SDv1.5mv-rawbox_2023-09-07_18-39_224x400/controlnet is not the path to a directory containing a config.json file. (Issue #119)





  
Maybe you can change the config "configs/model/SDv1.5mv-rawbox_t.yaml" line 12 "pretrained_magicdrive: **../**MagicDrive-pretrained/SDv1.5mv-rawbox_2023-09-07_18-39_224x400" to "pretrained_magicdrive: **./**MagicDrive-pretrained/SDv1.5mv-rawbox_2023-09-07_18-39_224x400" (delete the first point in the path)
  
I made the modifications according to your suggestion,but there is another mistake.Since I have  prepared the file as shown in the picture,I'm confused why the jpg file cannot be found.
 2024-11-26.201845.png (view on web)
 2024-11-26.202014.png (view on web)

**Comment by CSUXA** [comment]
> 是的，默认配置将尝试查找位于此处的模型（如自述文件中所示）：
> 
> ```
> {ROOT}/../MagicDrive-pretrained/
> └── SDv1.5mv-rawbox_2023-09-07_18-39_224x400
> ```
> 
> 而不是`{ROOT}/MagicDrive-pretrained/`
> 
> 像这样的错误通常表示找到预训练模型的路径错误。

You are quite right,I have reorganized the structure of the project to fix this error.Thanks for your help.

**Comment by CC-1997** [comment]
@TJXA Hi! I can't download the pretrained model, could you please share it with me? Thank you very much!
My email address:849099293@qq.com

**Comment by TJXA** [comment]
You can try changing the address to the HuggingFace mirror site: https://hf-mirror.com/
