### ISSUE TITLE
A issue about changing pre-trained model to SDv2.1

### ISSUE THREAD

**Issue by Miayui** [cure-lab/MagicDrive#129]
Hi, I want to change the pre-trained model to stable diffusion 2.1 in main branch, but I ran into some difficulties when load UNet. 
To change the pre-trained model, I I made the change to the code:
- Create config file `./config/model/SDv2.1mv_rawbow.yaml`, the main different with `./config/model/SDv1.5mv_rawbow.yaml` is:
```
change "pretrained_model_name_or_path"
change "controlnet.camera_out_dim" from 768 to 1024
change "controlnet.bbox_embedder_param.class_token_dim" from 768 to 1024 
change "controlnet.bbox_embedder_param.proj_dims" from [768, 512, 512, 768] to [1024, 512, 512, 1024]
```
After that, I run `accelerate launch --mixed_precision fp16 --gpu_ids all --num_processes 1 tools/train.py +exp=224x400 runner=1gpus`
And the terminal show:
```
...
[2024-12-17 03:34:14,024][root][INFO] - [UNet2DConditionModelMultiview] load pretrained with missing_keys: [down_blocks.0.attentions.0.transformer_blocks.0.norm4.weight, down_blocks.0.attentions.0.transformer_blocks.0.norm4.bias', ..., 'mid_block.attentions.0.transformer_blocks.0.connector.weight', 'mid_block.attentions.0.transformer_blocks.0.connector.bias']; unexpected_keys: []
...
```
The INFO was reported in `magicdrive.networks.unet_2d_condition_multiview.UNET2DConditionModelMultiview.from_unet_2d_condition`. So I thought maybe I should:
- Change  `__init__` in `magicdrive.networks.unet_2d_condition_multiview.UNET2DConditionModelMultiview` 
```
by compared SDv2.1's unet.config, I change:
1. corss_attention_dim: 1280 -> 1024
2. attention_head_dim: 8 -> (5, 10, 20, 20)
3. use_linear_projection: False -> True
4. upcast_attention: False -> True
```
But it still not work, could you give me some hints? Thank you so much!

**Comment by flymin** [comment]
Please be notified with #128. It is normal to see missing keys as we are adding modules to SD and partially loading the pre-trained model. They are not errors but helper INFO for you to double-check whether the parameters are loaded as expected.

The following parts seem fine to me.

> To change the pre-trained model, I I made the change to the code:
> - Create config file `./config/model/SDv2.1mv_rawbow.yaml`, the main different with `./config/model/SDv1.5mv_rawbow.yaml` is:
> ```
> change "pretrained_model_name_or_path"
> change "controlnet.camera_out_dim" from 768 to 1024
> change "controlnet.bbox_embedder_param.class_token_dim" from 768 to 1024 
> change "controlnet.bbox_embedder_param.proj_dims" from [768, 512, 512, 768] to [1024, 512, 512, 1024]
> ```


However, I do not think changing the default parameters helps, because we initialize the model with
https://github.com/cure-lab/MagicDrive/blob/d2fad7dd5056110afed07da821325eab84f967e8/magicdrive/runner/multiview_runner.py#L109
it will load the parameters from `${YOUR_PRETRAINED_MODEL}/unet/config.json` and override the detaults.
This is also reflected by the following lines, where you may need to take a closer look into it:
https://github.com/cure-lab/MagicDrive/blob/d2fad7dd5056110afed07da821325eab84f967e8/magicdrive/networks/unet_addon_rawbox.py#L431-L473

I took a quick look at SD2.0 and found that it keeps the same module for the UNet. Therefore, I do not think you need to change any `__init__` functions if in case that no errors were reported. However, please be reminded to also change the text encoder & tokenizer & vae for SD2.0.

**Comment by Miayui** [comment]
Oh, I understand. At first I saw so many missing keywords that I thought the model wasn't loading properly（＃－.－）
Thank you for your reply!
