### ISSUE TITLE
Some confusion about BEVFusion detection scores.

### ISSUE THREAD

**Issue by enhuima** [cure-lab/MagicDrive#2]
Hi, I would like to express my appreciation for your outstanding work. I have some further questions regarding the BEVFusion detection scores.

I notice that in the first and third rows of table 2 in your paper, the bevfusion detection scores you show without data augmentation are much lower than those officially reported by bevfusion (https://github.com/mit-han-lab/bevfusion/). This is very confusing.

Thank you, and I look forward to your response!
Best regards.

**Comment by flymin** [comment]
Hi, @enhuima.

Please find more detailed specifications in Appendix D. Since the bevfusion model seems to saturate quickly, we use different training epochs to show performance improvement. In short, the 2x in Table 6 should match their released configs, where we report the results from our reproduction.
