### ISSUE TITLE
video-branch occurs error when followed your steps [No such file or directory: './out/lidar_20Hz/results_nusc.json']

### ISSUE THREAD

**Issue by zhangxiao696** [cure-lab/MagicDrive#27]
![image](https://github.com/cure-lab/MagicDrive/assets/13326803/1fa3dc47-67ac-4af9-9fcb-ae615a0d549a)

<img width="827" alt="image" src="https://github.com/cure-lab/MagicDrive/assets/13326803/23e3cab6-ddba-47d0-962a-77747f8a227f">

hello, When I followed your steps, it reported an error, may I ask you how did you successfully execute it?

**Comment by zhangxiao696** [comment]
> I have some doubts, ASAP code was last updated two years ago, did you also execute successfully as mentioned above？

Their code has been frozen and has not been updated

**Comment by flymin** [comment]
Yes, we run their codes.

Let me talk more. Our codes do not load their modules but outputs, which means any annotation generation methods should be useful. We just recommend the one we used, which is also adopted by other literatures.

**Comment by zhangxiao696** [comment]
> Yes, we run their codes.
> 
> Let me talk more. Our codes do not load their modules but outputs, which means any annotation generation methods should be useful. We just recommend the one we used, which is also adopted by other literatures. Hope it helps.

okey, I get, thanks you a lot

**Comment by potentialming** [comment]
> > Yes, we run their codes.
> > Let me talk more. Our codes do not load their modules but outputs, which means any annotation generation methods should be useful. We just recommend the one we used, which is also adopted by other literatures. Hope it helps.
> 
> okey, I get, thanks you a lot

Did you finally solve the problem? Did you successfully complete the training? I commented out the relevant code of nusc_annotation_generator.py and successfully generated interp_12Hz_trainval, but when I ran bash scripts/prepare_dataset.sh, an error occurred KeyError: 'a5f12393fdf042a4a1c25cbe29f3f4ea'. Is it because the environment of the main branch was used when using the video branch?Hope to get your help.
`(mdrive) root@autodl-container-a95f1182e8-fba7c440:~/autodl-tmp/MagicDrive/MagicDrive-video# bash scripts/prepare_dataset.sh
======
Loading NuScenes tables for version interp_12Hz_trainval...
23 category,
8 attribute,
4 visibility,
911 instance,
12 sensor,
120 calibrated_sensor,
31206 ego_pose,
8 log,
10 scene,
35364 sample,
424368 sample_data,
1095571 sample_annotation,
4 map,
Done loading in 12.444 seconds.
======
Reverse indexing ...
Traceback (most recent call last):
  File "tools/create_data.py", line 109, in <module>
    nuscenes_data_prep(
  File "tools/create_data.py", line 34, in nuscenes_data_prep
    nuscenes_converter.create_nuscenes_infos(
  File "/root/autodl-tmp/MagicDrive/MagicDrive-video/tools/data_converter/nuscenes_converter.py", line 73, in create_nuscenes_infos
    nusc = NuScenes(version=version, dataroot=root_path, verbose=True)
  File "/root/miniconda3/envs/mdrive/lib/python3.8/site-packages/nuscenes/nuscenes.py", line 124, in __init__
    self.__make_reverse_index__(verbose)
  File "/root/miniconda3/envs/mdrive/lib/python3.8/site-packages/nuscenes/nuscenes.py", line 170, in __make_reverse_index__
    inst = self.get('instance', record['instance_token'])
  File "/root/miniconda3/envs/mdrive/lib/python3.8/site-packages/nuscenes/nuscenes.py", line 216, in get
    return getattr(self, table_name)[self.getind(table_name, token)]
  File "/root/miniconda3/envs/mdrive/lib/python3.8/site-packages/nuscenes/nuscenes.py", line 225, in getind
    return self._token2ind[table_name][token]
KeyError: 'a5f12393fdf042a4a1c25cbe29f3f4ea'
Traceback (most recent call last):
  File "tools/prepare_map_aux.py", line 12, in <module>
    from mmdet3d.datasets.pipelines.loading_utils import one_hot_encode, one_hot_decode
ImportError: cannot import name 'one_hot_encode' from 'mmdet3d.datasets.pipelines.loading_utils' (/root/autodl-tmp/MagicDrive/third_party/bevfusion/mmdet3d/datasets/pipelines/loading_utils.py)
Traceback (most recent call last):
  File "tools/prepare_map_aux.py", line 12, in <module>
    from mmdet3d.datasets.pipelines.loading_utils import one_hot_encode, one_hot_decode
ImportError: cannot import name 'one_hot_encode' from 'mmdet3d.datasets.pipelines.loading_utils' (/root/autodl-tmp/MagicDrive/third_party/bevfusion/mmdet3d/datasets/pipelines/loading_utils.py)`

**Comment by potentialming** [comment]
> > Yes, we run their codes.
> > Let me talk more. Our codes do not load their modules but outputs, which means any annotation generation methods should be useful. We just recommend the one we used, which is also adopted by other literatures. Hope it helps.
> 
> okey, I get, thanks you a lot

Did you finally solve the problem? Did you successfully complete the training? I successfully generated interp_12Hz_trainval by commenting out the relevant code of nusc_annotation_generator.py, but when I ran bash scripts/prepare_dataset.sh, an error occurred KeyError: 'a5f12393fdf042a4a1c25cbe29f3f4ea'. Is it because the environment of the main branch was used when using the video branch? Hope to get your help.
![image](https://github.com/cure-lab/MagicDrive/assets/113165075/0c60bb3d-8b0a-431f-b5a0-15e515c671b9)

**Comment by LeningWang** [comment]
> > > Yes, we run their codes.
> > > Let me talk more. Our codes do not load their modules but outputs, which means any annotation generation methods should be useful. We just recommend the one we used, which is also adopted by other literatures. Hope it helps.
> > 
> > 
> > okey, I get, thanks you a lot
> 
> Did you finally solve the problem? Did you successfully complete the training? I successfully generated interp_12Hz_trainval by commenting out the relevant code of nusc_annotation_generator.py, but when I ran bash scripts/prepare_dataset.sh, an error occurred KeyError: 'a5f12393fdf042a4a1c25cbe29f3f4ea'. Is it because the environment of the main branch was used when using the video branch? Hope to get your help. ![image](https://private-user-images.githubusercontent.com/113165075/329780629-0c60bb3d-8b0a-431f-b5a0-15e515c671b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNzk5MzQsIm5iZiI6MTcxODM3OTYzNCwicGF0aCI6Ii8xMTMxNjUwNzUvMzI5NzgwNjI5LTBjNjBiYjNkLThiMGEtNDMxZi1iNWEwLTE1ZTUxNWM2NzFiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNFQxNTQwMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZWRkNGZmNGJmNmRjZjljNDU0MGExZmNiZGMwNGY1ZDNjZGNkNzA3M2ExNzU0Y2NmZTRkNjg3ODNmMjg3NGY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gcZxVBInPP2ah06r-zgvMLz8G0s8KKq1sNhjzshKBY0)

I have same problem

**Comment by flymin** [comment]
For you guys still having this issue. We will release the processed data annotations tmr, please wait for the updates in [w-coda2024 track2](https://coda-dataset.github.io/w-coda2024/track2/).

**Comment by dyy0205** [comment]
> > > Yes, we run their codes.
> > > Let me talk more. Our codes do not load their modules but outputs, which means any annotation generation methods should be useful. We just recommend the one we used, which is also adopted by other literatures. Hope it helps.
> > 
> > 
> > okey, I get, thanks you a lot
> 
> Did you finally solve the problem? Did you successfully complete the training? I successfully generated interp_12Hz_trainval by commenting out the relevant code of nusc_annotation_generator.py, but when I ran bash scripts/prepare_dataset.sh, an error occurred KeyError: 'a5f12393fdf042a4a1c25cbe29f3f4ea'. Is it because the environment of the main branch was used when using the video branch? Hope to get your help. ![image](https://private-user-images.githubusercontent.com/113165075/329780629-0c60bb3d-8b0a-431f-b5a0-15e515c671b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NzY2NzQsIm5iZiI6MTcxOTQ3NjM3NCwicGF0aCI6Ii8xMTMxNjUwNzUvMzI5NzgwNjI5LTBjNjBiYjNkLThiMGEtNDMxZi1iNWEwLTE1ZTUxNWM2NzFiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QwODE5MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNTdhNDU5MzBmMmJlZjI1NmZkOTdmN2NjYWZlYjU1NWVhNDdiYWU1OWRkN2FmYmI5OTQ3NTY1N2I2MGM1MmZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DTN8QJluSWlvEGMYQOolP58V7tLDFvqLpauPdtEyfIc)
Have you solved the KeyError problem?
