### ISSUE TITLE
Did the neg_prompt really work? i typed in "tree" to neg_prompt, try to remove the tree in scene, but failed!

### ISSUE THREAD

**Issue by cam-ai** [cure-lab/MagicDrive#42]

**Comment by flymin** [comment]
Sorry, we did not test that.

Even though the implementation is correct, I do not think "tree" will work because there is no "tree" in the caption of nuScenes. You may think of other use cases and try. 

For now, I just checked that negative prompts do affect the generation. Personally, however, I do not provide any guarantee for the implementation related to "negative prompts".

**Comment by cam-ai** [comment]
Got it!
