### ISSUE TITLE
The training time for the entire nuscenes dataset is too long

### ISSUE THREAD

**Issue by zhaoyangwei123** [cure-lab/MagicDrive#60]
The training time for the entire nuscenes dataset is too long，have you considered training on other small datasets, such as nuscenes mini or kitti datasets?

**Comment by Yourlh** [comment]
+1

**Comment by flymin** [comment]
No. Even with full nuScenes, the generalization ability is limited and possibly more data is need. Smaller datasets may only overfit.

I think you are talking about the video generation rather than image generation. Also see #61.

Also duplicate with #9. 

If you are interested in either topic, please discuss there. I will close this.
