### ISSUE TITLE
About conditional embedding

### ISSUE THREAD

**Issue by qiuzidian** [cure-lab/MagicDrive#76]
Hi, great job! I would like to know that, you embedded the camera and box conditions to cross attention together with text embedding, but didn't finetune the cross attention, why? Will input that is different from the original text embedding cause any problems?

**Comment by flymin** [comment]
Hi, the cross-attention is not trainable because we want to 
1. train as few parameters as possible;
2. keep the generalization effect of text embeddings.

As shown by the results, 1 works well but 2 failed. You can try different texts by keeping other conditions the same. I did not see much difference.
